### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by hurrymaplelad** [garann/template-chooser#16]
I'd love to put together a pull request to add [Teacup](http://goodeggs.github.com/teacup/) but looks like this project hasn't changed in months.  Anyone home?

**Comment by garann** [comment]
Yep, still alive. However, I haven't seen a lot of new template engines show up getting anywhere close to the traction of even the more esoteric on the list, so it hasn't felt like there's much to add, and now people are tending toward frameworks for use cases where templates might be clearly wanted so I'm not sure how many more updates there will be.

**Comment by hurrymaplelad** [comment]
Great!  Pull request pending
