### ISSUE TITLE
Add transparency and fill to the repositories

### ISSUE THREAD

**Issue by Stwissel** [garann/template-chooser#2]
These templates use HTML attributes for targeting. So client and server work can be combined since an executed template has the same target markers as the raw one.

https://github.com/leonidas/transparency
https://github.com/profit-strategies/fill
(There's a Java port of fill: https://github.com/Stwissel/jfill)

**Comment by garann** [comment]
Transparency looks interesting. I'll try to play around with it and answer the filtering questions, or you can make a pull request? 

Fill's big "not ready for production" header makes me think it might be ok to chill on that for a while. :)

**Comment by Stwissel** [comment]
The "not ready for production" probably stems from the stated goal "eliminate directives" which hasn't been completed yet. I like the ability to add attributes using _attributeName (while it would have use @attributeName). What I was wondering with all the templates is: repeatability.
Meaning: Can I reapply the dataset to the _result_ of the tranformation _again_ and will get the same result. Use case mainly is templates that work on server and browser. Idea there: the initial page is rendered on the server and send as filled HTML to a browser (so Google could spider it) while updates come as JSON and are applied in the browser.
The really interesting question there are all the repeats. e.g. a JSON dataset renders 5 entries but the new set only has 3. A really interesting challenge.

I have to admit I haven't wrapped my head around pull requests yet [blush]

**Comment by garann** [comment]
Whatever the reasoning behind it, if they say it's not production-ready, I'm inclined to take them at face value. :)

Added transparency.
