### ISSUE TITLE
Nunjucks?

### ISSUE THREAD

**Issue by aramk** [garann/template-chooser#22]
It's pretty decent, ended up choosing it over handlebars. Here's my comparison, along with dust.js:

https://docs.google.com/document/d/15ln-DLS6ENFgRdnQJ-I1Ku9HMYwDvbvxnl-p761geTI/edit?usp=drive_web

**Comment by garann** [comment]
Working on it in PR #25. :)

**Comment by aramk** [comment]
:thumbsup:
