### ISSUE TITLE
Request to add Contemplate Engine

### ISSUE THREAD

**Issue by foo123** [garann/template-chooser#30]
Hi,

this is just a request (no hard feelings if it is not granted)

to include  a template engine of mine [Contemplate](https://github.com/foo123/Contemplate)

Thanks

**Comment by garann** [comment]
See comments on #31

**Comment by foo123** [comment]
No problem

the status is that no new features (in todo list) are added, due to other reasons
however if any bug needs fix, it is fixed

Since the app is only for well-known engines,, i guess it does not qualify
although i would not consider such a reason myself.

Anyway as said before, it is ok

**Comment by garann** [comment]
Admittedly only including popular engines is a little arbitrary, but as with most things JavaScript, I think if I tried to be comprehensive I'd be dealing with a lot of tools and would have to think of several additional ways to differentiate between them. Thank you for understanding. :)
