### ISSUE TITLE
Doesn't work in Opera

### ISSUE THREAD

**Issue by Poetro** [garann/template-chooser#4]
The transparency changing doesn't work in Opera, so the whole chooser is useless without actually seeing any results in Opera 11.62, the current stable version of Opera. There should be at least some fallback for browsers that don't do animation.

**Comment by martinkadlec0** [comment]
I pushed commit that makes it working at least in Opera 12. ;)

**Comment by garann** [comment]
@Poetro because this is just a way of presenting a little research, I'm not going to worry a lot about browser support, particularly in this case because Opera _is_ going to support animations. With @BS-Harou's fix it should soon work for Opera users, as well, and I think that's adequate.

**Comment by Poetro** [comment]
Thank you for your response, and I understand the reasoning behind it.
