### ISSUE TITLE
Live website does not work

### ISSUE THREAD

**Issue by bookercodes** [garann/template-chooser#47]
I just found this website via Google but it does not seem to work. 

![](http://i.imgur.com/RwSONKX.png)

**Comment by garann** [comment]
If you take a look at the README, you'll see my argument for why this tool is probably no longer useful to you, _however_ if you'd like to decide that for yourself, just try it without HTTPS: http://garann.github.io/template-chooser

**Comment by bookercodes** [comment]
Whoopsy. I completely neglected to read the readme. 

And I did try to use the website without HTTPs but I forgot I had [HTTPS Everwhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en) enabled.

My bad and thank you!

**Comment by garann** [comment]
Heh, no worries, I could probably add uncooperativeness with HTTPS to the list of reasons. ;)
