### ISSUE TITLE
Consider including Transparency as one of the fastest template engines

### ISSUE THREAD

**Issue by jkeskikangas** [garann/template-chooser#8]
Hi,

Thanks for the cool site and including Transparency in the comparison!

One question, though. I wonder how the template engine performance is evaluated? 

Based on performance tests I've run, transparency should be easily one of the fastest engines on the client side. The server-side is a different story though, as usually string templating is usually a clear win over there.

Here's the tests I've run:

http://jsperf.com/transparency-vs-handlebars-finite-list/8
http://jsperf.com/transparency-vs-handlebars-infinite-list/7

http://jsperf.com/dom-vs-innerhtml-based-templating/366 (kind of naive test, as transparency caches aggressively)

Cheers,

Jarno

**Comment by garann** [comment]
I (somewhat arbitrarily) decided that this jsperf would be the test: http://jsperf.com/javascript-templating-shootoff-extended/25 Want to add Transparency there?

**Comment by jkeskikangas** [comment]
I'd need to do quite a bit of changes :) If that's ok for you, I can take a look later at evening. 

It seems that the test just calls rendering functions, but misses the point that some of them are string based, while other are DOM based.

That's kind of same than comparing apples to oranges. 

In the browser, the results needs to be eventually in the DOM, in order to get shown to the user. With string based templates, it means assigning the result to the `innerHTML` property of the container element. That triggers browser's HTML parser, which is the biggest bottleneck for any string based template engine.

That's also one of the main reasons Transparency is faster than pretty much anything else, while rendering in the browser.

From that point of view, the tests I mentioned above got it right.

Of course, server-side templating is a different story. There the HTML string is actually the end result, which is sent to the client. So on the server-side, string based templates beats DOM based hands down.

**Comment by garann** [comment]
Since this tool is comparing both string- and DOM-based engines, apples to oranges is kind of a necessary part of what it does. That's why I like this test - I feel it gives both a more or less fair shot. Rather than forking the jsperf to change the test (which would miss the point), it sounds like what you might want is to fork this project to just compare DOM-based templating engines? I'll go ahead and close this issue, since rendering speed is the metric the tool is looking at.

**Comment by jkeskikangas** [comment]
We'll, it does not give a fair shot and is indeed flawed for client-side comparison (where, I believe, majority of js templates are used). 

Given the template engine is used on the client side, the only reasonable point of measure is "Time used to produce visible DOM elements with the given data". That's the real goal of any template engine. 

Anything less, and the test is comparing all sorts of half-baked recipes. Particularly, result strings are not even halfway there.

Anyway, I'm fine with the resolution. Thanks for the visibility and the appealing site.
